/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiError { 
    /**
     * Fehlercode
     */
    code: ApiError.CodeEnum;
    /**
     * Menschlich lesbare Beschreibung.
     */
    message: string;
}
export namespace ApiError {
    export const CodeEnum = {
        BadRequest: 'BAD_REQUEST',
        NotFound: 'NOT_FOUND',
        ServerError: 'SERVER_ERROR'
    } as const;
    export type CodeEnum = typeof CodeEnum[keyof typeof CodeEnum];
}


