/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Document { 
    id?: string;
    document?: string;
    documentNo?: number | null;
    dokumentTyp?: string | null;
    confidence?: number | null;
    createdAt?: string | null;
    category?: Document.CategoryEnum | null;
    firstName?: string | null;
    surname?: string | null;
    vsnr?: string | null;
    birthDate?: string | null;
    summary?: string | null;
    erkannteEntitaeten?: { [key: string]: any; } | null;
    dokumentenstapelId?: string;
}
export namespace Document {
    export const CategoryEnum = {
        Ausweis: 'AUSWEIS',
        Geburtsurkunde: 'GEBURTSURKUNDE',
        Sterbeurkunde: 'STERBEURKUNDE',
        Zeugnis: 'ZEUGNIS',
        Steuerbescheid: 'STEUERBESCHEID',
        Krankenkassenbescheinigung: 'KRANKENKASSENBESCHEINIGUNG',
        Sonstige: 'SONSTIGE'
    } as const;
    export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];
}


