/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageNoContent { 
    seiteId?: string;
    pageNo?: number;
    pdfPagePath?: string;
    sha256?: string;
    status?: string;
    errorMessage?: string | null;
    dokumentenstapelId?: string;
    seitenExtraktId?: string | null;
    createdAt?: string;
    usable?: boolean;
}

