/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PageExtractResponse { 
    pageId: string;
    text: string;
    markdown: string;
    doclingJson: { [key: string]: object; };
}

