/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Page { 
    stapelId?: string;
    pageNo?: number;
    pdf?: string;
    pdfPagePath?: string;
    sha256?: string;
    status?: string;
    errorMessage?: string | null;
    extractedText?: string | null;
    dokumentenstapelId?: string;
    seitenExtraktId?: string | null;
    createdAt?: string;
    usable?: boolean;
}

