/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonNullableString } from './jsonNullableString';


export interface PageInfo { 
    pageId: string;
    pageNo: number;
    status: string;
    errorMessage?: JsonNullableString;
}

