/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SeitenExtrakt { 
    id?: string;
    seiteId?: string;
    markdown?: string | null;
    doclingJson?: string | null;
    ocrEngine?: string | null;
    extractedAt?: string | null;
}

