/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StapelProgress { 
    stapelId: string;
    status: string;
    pagesTotal: number;
    pagesDone: number;
    pagesFailed: number;
}

