/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Versicherter { 
    id?: string;
    vorname?: string | null;
    nachname?: string | null;
    vsnr?: string;
    geburtsdatum?: string | null;
    createdAt?: string;
}

