/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VorgangPageResult } from './vorgangPageResult';


export interface VorgangStapelResult { 
    stapelId: string;
    stapelName: string;
    status: string;
    pages: Array<VorgangPageResult>;
}

