/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Vorgang { 
    id?: string;
    versicherterId?: string;
    status?: string;
    createdAt?: string | null;
    updatedAt?: string | null;
    progress?: number;
    summary?: string | null;
    errorCode?: string | null;
    errorMessage?: string | null;
    dokumentenstapelIds?: Array<string>;
}

