/**
 * TheLionKing
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StapelProgress } from './stapelProgress';


export interface VorgangWorkflowStatusResponse { 
    vorgangId: string;
    status: string;
    pagesTotal: number;
    pagesDone: number;
    pagesFailed: number;
    stapel: Array<StapelProgress>;
}

