/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VorgangStapelResult } from './vorgangStapelResult';


export interface VorgangResultsResponse { 
    vorgangId: string;
    status: string;
    stapel: Array<VorgangStapelResult>;
}

