/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonNullableString } from './jsonNullableString';


export interface VorgangPageResult { 
    pageId: string;
    pdfUrl: string;
    pageNo: number;
    status: string;
    errorMessage?: JsonNullableString;
    text: string;
    markdown: string;
    doclingJson: { [key: string]: object; };
}

